### PR TITLE
batches: Test internal packages

### PR DESCRIPTION
**Pull request by BolajiOlajide**
Add tests for internal

### CODE REVIEW

**Review by courier-new — APPROVED** [review]
Looks fine to me. Just to clarify for my own understanding, which parts of this are new code, and which parts are from the Go Tools internal package?

**Comment by BolajiOlajide** [comment]
> Looks fine to me. Just to clarify for my own understanding, which parts of this are new code, and which parts are from the Go Tools internal package?

Most of the code here is from the Go tools internal package, with some edit to accommodate some changes we made such as [this](https://github.com/sourcegraph/go-diff-patch/commit/702699797c2bb0c4b99c156064f56d6cfa743c30) - for context, the diff generated when all lines are deleted wasn't correct so that commit fixes it.

That's mostly it @courier-new .

**Comment by courier-new** [comment]
Ah okay great, thanks for the info!

**Review by Piszmog — APPROVED** [review]
LGTM!

Would be nice to have a followup Issue to add benchmarks in here to understand the performance.

**Comment by BolajiOlajide** [comment]
> LGTM!
> 
> Would be nice to have a followup Issue to add benchmarks in here to understand the performance.

Done. [#40489](https://github.com/sourcegraph/sourcegraph/issues/40489)

**Pull request merged**
